import Head from 'next/head';
import Layout from '../components/layout';
export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>About Me | The Full Body Lab</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="/CopyTrial-Regular.woff"
            as="font"
            type="font/woff"
            crossOrigin
          />
        </Head>
      </div>
    </Layout>
  );
}
