import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '../components/hero';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';

const aboutMeQuery = groq`*[_type == "aboutMePage"][0]{
  title,
  header,
  eyebrow,
}`;

export default function AboutMe({ initialData, preview }) {
  const { data } = usePreviewSubscription(aboutMeQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <div>
        <Head>
          <title>{data.title} | The Full Body Lab</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Hero data={data} />
      </div>
      {/* https://codepen.io/liborgabrhel/pen/Ljzwxe */}
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const data = await querySanity(aboutMeQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
