import Head from 'next/head';
import Layout from '../components/layout';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';
import Hero from '../components/hero';
import ReactMarkdown from 'react-markdown';

const contactQuery = groq`*[_type == "contactPage"][0]{
  title,
  header,
  eyebrow,
  body,
}`;

export default function Contact({ initialData, preview }) {
  const { data } = usePreviewSubscription(contactQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <Head>
        <title>Contact | The Full Body Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/CopyTrial-Regular.woff" as="font" type="font/woff" crossOrigin />
      </Head>
      <Hero data={data} />
      <section className="fblSection flexBetween">
        <div className="copyBlock">
          <ReactMarkdown>{data.body}</ReactMarkdown>
        </div>
        <div className="linkBlock">
          <p>
            <span role="presentation" className="emoji">
              ✉️
            </span>
            <a className="textLink" href="https://calendly.com/thefullbodylab/discovery-call">
              Schedule a call
            </a>
          </p>
          <p>
            <span role="presentation" className="emoji">
              📱
            </span>
            <a className="textLink" href="mailto:mishaun@thefullbodylab.com">
              Email me
            </a>
          </p>
        </div>
      </section>
    </Layout>
  );
}
export async function getStaticProps({ preview = false }) {
  const data = await querySanity(contactQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
