import Head from 'next/head';
import Layout from '../components/layout';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';
import StyledMarkdown from '../components/styledMarkdown';
import Hero from '../components/hero';
import classNames from 'classnames';
import $ from './faq.module.css';
const faqQuery = groq`*[_type == "faqPage"][0]{
  title,
  header,
  eyebrow,
  faqBlocks[],
}`;

const metaQuery = groq`*[_type == "siteSettings"][0]{
  title,
  description
}`;

export default function FAQ({ metaData, initialData, preview }) {
  const { data } = usePreviewSubscription(faqQuery, { initialData, enabled: preview });
  return (
    <Layout title={data.title} metaData={metaData}>
      <Head>
        <title>{data.title} | The Full Body Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/CopyTrial-Regular.woff"
          as="font"
          type="font/woff"
          crossOrigin="true"
        />
      </Head>
      <Hero data={data} />
      <section className={classNames($.faqSection, 'fblSection')}>
        {data.faqBlocks.map(block => (
          <details className={$.block} key={block._key}>
            <summary>{block.question}</summary>
            <StyledMarkdown>{block.answer}</StyledMarkdown>
          </details>
        ))}
      </section>
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const data = await querySanity(faqQuery);
  const metaData = await querySanity(metaQuery);

  return {
    props: {
      initialData: data,
      metaData,
      preview
    }
  };
}
