import Head from 'next/head';
import Layout from '../components/layout';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';
import ReactMarkdown from 'react-markdown';
import Hero from '../components/hero';
import classNames from 'classnames';
import $ from './faq.module.css';
const faqQuery = groq`*[_type == "faqPage"][0]{
  title,
  header,
  eyebrow,
  faqBlocks[],
}`;

export default function FAQ({ initialData, preview }) {
  const { data } = usePreviewSubscription(faqQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <Head>
        <title>{data.title} | The Full Body Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/CopyTrial-Regular.woff" as="font" type="font/woff" crossOrigin />
      </Head>
      <Hero data={data} />
      <section className={classNames($.faqSection, 'fblSection')}>
        {data.faqBlocks.map(block => (
          <details className={$.block} key={block.key}>
            <summary>{block.question}</summary>
            <ReactMarkdown className={$.answer}>{block.answer}</ReactMarkdown>
          </details>
        ))}
      </section>
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const data = await querySanity(faqQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
