import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '../components/hero';
import { querySanity, usePreviewSubscription } from '../lib/sanity';
import { groq } from 'next-sanity';
import Triptych from '../components/triptych';
import Intro from '../components/intro';
import Testimonial from '../components/testimonial';
const homeQuery = groq`*[_type == "homePage"][0]{
  title,
  header,
  eyebrow,
  teaser[] {
    ...,
    image {
      asset->
    }
  },
  introHeader,
  introCopy,
  testimonialName,
  testimonialQuotation,
}`;

export default function Home({ initialData, preview }) {
  const { data } = usePreviewSubscription(homeQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <Head>
        <title>The Full Body Lab | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero className="bgSage" data={data} />
      <Intro data={data} />
      <Triptych data={data.teaser} />
      <Testimonial data={data} />
    </Layout>
  );
}
export async function getStaticProps({ preview = false }) {
  const data = await querySanity(homeQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
