import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '../components/hero';
import Packages from '../components/packages';
import Goals from '../components/goals';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';
import Link from 'next/link';

const servicesQuery = groq`*[_type == "servicesPage"][0]{
  title,
  header,
  eyebrow,
  packages[],
  goalsHeader,
  goalsList[],
}`;

export default function services({ initialData, preview }) {
  const { data } = usePreviewSubscription(servicesQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <div>
        <Head>
          <title>{data.title} | The Full Body Lab</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Hero data={data} />
        <Goals data={data} />
        <Packages data={data.packages} />
      </div>
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const data = await querySanity(servicesQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
