import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '../components/hero';
import { groq } from 'next-sanity';
import { querySanity, usePreviewSubscription } from '../lib/sanity';

const servicesQuery = groq`*[_type == "servicesPage"][0]{
  title,
  header,
  eyebrow,
}`;

export default function services({ initialData, preview }) {
  const { data } = usePreviewSubscription(servicesQuery, { initialData, enabled: preview });
  return (
    <Layout>
      <div>
        <Head>
          <title>{data.title} | The Full Body Lab</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="/CopyTrial-Regular.woff"
            as="font"
            type="font/woff"
            crossOrigin
          />
        </Head>
        <Hero data={data} />
      </div>
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const data = await querySanity(servicesQuery);

  return {
    props: {
      initialData: data,
      preview
    }
  };
}
